### ISSUE TITLE
Auto-toggle to available quote currency

### ISSUE THREAD

**Issue by coretechs** [altangent/cryptolist#28]
On a clean load of the site, clicking on a non-USD pair (e.g. EOS) results in a message -
"No markets found for selected currency pair. Please select a different quote currency"

A more preferable behavior would be to automatically toggle and display a chart for an available trading pair for the selected currency.

**Comment by camray** [comment]
This seems like a difficult technical problem. A nice work around might be using the new secondary quote currency and deriving non-existent markets in blocktap. Thoughts?
