### ISSUE TITLE
Display full trading pair symbols

### ISSUE THREAD

**Issue by coretechs** [altangent/cryptolist#29]
Right now we only display the currency code in parenthesis under the name:

Bitcoin
(BTC)

In order to tell what the quote symbol is you need to reference the drop-down toggle in the upper right corner of the window.

I suggest moving the drop-down toggle for the quote currency to appear directly below the name of the crypto-currency and make it part of the currency code display:

Bitcoin
BTC / [USD]

This would also address the issue in #28 as you could auto-select the first entry available in the drop down for a particular crypto.

**Comment by camray** [comment]
Addressed [here](https://github.com/altangent/cryptolist/commit/631e0dbe34e52e23403fd208a44dfe0ed3d19fc4#diff-843387ec6df2994f3436ce00755abd3fR175)
