### ISSUE TITLE
Volume Bars Coloring 

### ISSUE THREAD

**Issue by pgh412** [altangent/cryptolist#32]
![screen shot 2018-09-04 at 4 58 11 pm](https://user-images.githubusercontent.com/37389626/45057489-be8d9200-b063-11e8-9a5c-f83a4752e80c.png)

Add Green and Red colors to the volume bars. 

If the price went up in that bar's timeframe, bar is green, if the price went down in the bar's time frame the bar is red.

**Comment by camray** [comment]
<img width="788" alt="screen shot 2018-09-04 at 7 41 14 pm" src="https://user-images.githubusercontent.com/4270079/45063147-880f4180-b07a-11e8-85ea-7cae6cdd7eb3.png">

**Comment by camray** [comment]
9c9e29cb219b8b98827ba30b42d9ec4e7b603d87
