### ISSUE TITLE
Move Historical Data to separate tab

### ISSUE THREAD

**Issue by camray** [altangent/cryptolist#48]
Move the HistoricalData component to its own tab in Switcher.jsx

Add a toolbar with dropdown options to set exchange and resolution

**Comment by inovux** [comment]
I could help on this :)

**Comment by camray** [comment]
@inovux perfect! I’ll assign it to you. Let me know if you need anything

**Comment by camray** [comment]
@inovux 🤷‍♂️ I guess I can’t assign it to you. But I’ll get a notification when you send a PR 😃

**Comment by inovux** [comment]
Im getting a cors error on localhost with your current version

**Comment by camray** [comment]
@inovux Got it. Looks like you'll need to use your local server for the GraphQL requests. As a temporary fix I've updated the instructions on the README. You'll need to grab an API key from blocktap.io then let me know when you've done that and I'll give you OSS dev permissions.

**Comment by inovux** [comment]
@camray Thanks, working on it now.
