### ISSUE TITLE
Create Trades tab 

### ISSUE THREAD

**Issue by camray** [altangent/cryptolist#49]
Add another tab for trades in the [switcher](https://github.com/altangent/cryptolist/blob/master/src/client/scenes/crypto-deep-info/components/switcher.jsx)

Move [Historical Data from Chart](https://github.com/altangent/cryptolist/blob/master/src/client/scenes/crypto-deep-info/components/chart.jsx#L166) to it's own file

**Comment by lkwc33** [comment]
I'm new here.  I would like to jump in but not sure what to do?

**Comment by camray** [comment]
Hi @lkwc33! Drop me an email, cray@altangent.com for an api token. After that, clone the repo, and put the API token in [the config file](https://github.com/altangent/cryptolist/blob/master/config.json#L3). 

You should be able to run `npm run watch` and see cryptolist on `localhost:8000`

I can answer any additional questions here or over email
